openapi: 3.0.3
info:
  title: Users API
  description: API for retrieving user list
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server
paths:
  /users:
    get:
      summary: Get all users
      description: Retrieves a list of all users from the database. Returns all users without pagination.
      operationId: getUsers
      tags:
        - Users
      responses:
        '200':
          description: Successfully retrieved list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  username: "johndoe"
                  email: "john@example.com"
                - id: 2
                  username: null
                  email: "jane@example.com"
                - id: 3
                  username: "bobsmith"
                  email: "bob@example.com"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "An error occurred while processing your request."
components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int32
          description: Unique identifier for the user
          example: 1
        username:
          type: string
          nullable: true
          description: Optional username. Must be unique when present.
          example: "johndoe"
        email:
          type: string
          format: email
          description: Required email address. Must be unique.
          example: "john@example.com"
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "An error occurred while processing your request."

